/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.neoforged.neoforge.common.ModConfigSpec
 *  net.neoforged.neoforge.common.ModConfigSpec$BooleanValue
 *  net.neoforged.neoforge.common.ModConfigSpec$Builder
 *  net.neoforged.neoforge.common.ModConfigSpec$ConfigValue
 *  net.neoforged.neoforge.common.ModConfigSpec$IntValue
 */
package com.inventorypets.config;

import com.inventorypets.fabric.config.ModConfigSpec;

public class InventoryPetsConfig {
    public static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();
    public static final ModConfigSpec SPEC;
    public static ModConfigSpec.BooleanValue petsMustEat;
    public static ModConfigSpec.BooleanValue petsEatWholeItems;
    public static ModConfigSpec.BooleanValue disableAllDungeons;
    public static ModConfigSpec.BooleanValue disableNetherDungeons;
    public static ModConfigSpec.BooleanValue disableUndergroundDungeons;
    public static ModConfigSpec.BooleanValue disableSkyDungeons;
    public static ModConfigSpec.BooleanValue disableSeaCaveDungeons;
    public static ModConfigSpec.BooleanValue disableSpaceDungeons;
    public static ModConfigSpec.BooleanValue disableTreeTops;
    public static ModConfigSpec.BooleanValue disableMobsSpawnInDungeons;
    public static ModConfigSpec.BooleanValue disableSquidSpeed;
    public static ModConfigSpec.BooleanValue disableCreeperExplosion;
    public static ModConfigSpec.BooleanValue disableCloudLightning;
    public static ModConfigSpec.BooleanValue disableCloudSound;
    public static ModConfigSpec.BooleanValue dingotIPStruturesOnly;
    public static ModConfigSpec.BooleanValue disableEndermanAutoTeleport;
    public static ModConfigSpec.BooleanValue disablePingotAutoExtract;
    public static ModConfigSpec.BooleanValue disableSpongeWaterAbsorb;
    public static ModConfigSpec.BooleanValue disableIlluminatiGiveItems;
    public static ModConfigSpec.BooleanValue disableRightClickMachines;
    public static ModConfigSpec.BooleanValue illuminatiCraftedOnly;
    public static ModConfigSpec.BooleanValue reduceQuantumCrystalMonsterMinions;
    public static ModConfigSpec.BooleanValue disableSpiderJump;
    public static ModConfigSpec.BooleanValue disablePetsGiveItems;
    public static ModConfigSpec.BooleanValue disableSlimeReviveSound;
    public static ModConfigSpec.BooleanValue enableBlackHoleAffectsPlayers;
    public static ModConfigSpec.BooleanValue enablePufferfishAffectsPlayers;
    public static ModConfigSpec.BooleanValue enableMoonAffectsPlayers;
    public static ModConfigSpec.BooleanValue enableDubstepAffectsPlayers;
    public static ModConfigSpec.BooleanValue enableSunAffectsPlayers;
    public static ModConfigSpec.BooleanValue showSuggestors;
    public static ModConfigSpec.BooleanValue showUpdateMessage;
    public static ModConfigSpec.BooleanValue showHolidayMessages;
    public static ModConfigSpec.BooleanValue allPlayersMustBeInBed;
    public static ModConfigSpec.BooleanValue disableHolidayPets;
    public static ModConfigSpec.BooleanValue disableAprilFoolHoliday;
    public static ModConfigSpec.BooleanValue yearroundAprilFool;
    public static ModConfigSpec.BooleanValue enableAprilFoolGriefPranks;
    public static ModConfigSpec.BooleanValue allowPetrifierLegendaries;
    public static ModConfigSpec.BooleanValue disablePetrifier;
    public static ModConfigSpec.BooleanValue disableTreeTopTNT;
    public static ModConfigSpec.BooleanValue enableLootWithFTBUltimine;
    public static ModConfigSpec.BooleanValue disableCloudFly;
    public static ModConfigSpec.BooleanValue cowPetRemovesLevitation;
    public static ModConfigSpec.IntValue illuminatiCooldown;
    public static ModConfigSpec.IntValue illuminatiInvisibleDuration;
    public static ModConfigSpec.IntValue illuminatiItemCapLimit;
    public static ModConfigSpec.IntValue juggernautCooldown;
    public static ModConfigSpec.IntValue juggernautShieldWallDuration;
    public static ModConfigSpec.IntValue frequencySkyDungeons;
    public static ModConfigSpec.IntValue frequencyUndergroundDungeons;
    public static ModConfigSpec.IntValue frequencySeaCaveDungeons;
    public static ModConfigSpec.IntValue frequencyTreeTops;
    public static ModConfigSpec.IntValue frequencySpaceDungeons;
    public static ModConfigSpec.IntValue frequencyNetherDungeons;
    public static ModConfigSpec.IntValue petEatTimerFactor;
    public static ModConfigSpec.IntValue holidayPetMonth;
    public static ModConfigSpec.IntValue pacManPowerupFactor;
    public static ModConfigSpec.IntValue cloudFlySpeed;
    public static ModConfigSpec.IntValue biomeSearchChunks;
    public static ModConfigSpec.IntValue spongeAbsorbBlockRadius;
    public static ModConfigSpec.IntValue chickenEffectLevel;
    public static ModConfigSpec.IntValue pacManEatLevel;
    public static ModConfigSpec.ConfigValue<String> foodAnvil;
    public static ModConfigSpec.ConfigValue<String> foodApple;
    public static ModConfigSpec.ConfigValue<String> foodAprilFool;
    public static ModConfigSpec.ConfigValue<String> foodBanana;
    public static ModConfigSpec.ConfigValue<String> foodBed;
    public static ModConfigSpec.ConfigValue<String> foodBiome;
    public static ModConfigSpec.ConfigValue<String> foodBlackHole;
    public static ModConfigSpec.ConfigValue<String> foodBlaze;
    public static ModConfigSpec.ConfigValue<String> foodBrewingStand;
    public static ModConfigSpec.ConfigValue<String> foodCheetah;
    public static ModConfigSpec.ConfigValue<String> foodChest;
    public static ModConfigSpec.ConfigValue<String> foodChicken;
    public static ModConfigSpec.ConfigValue<String> foodCloud;
    public static ModConfigSpec.ConfigValue<String> foodCobblestone;
    public static ModConfigSpec.ConfigValue<String> foodCow;
    public static ModConfigSpec.ConfigValue<String> foodCraftingTable;
    public static ModConfigSpec.ConfigValue<String> foodCreeper;
    public static ModConfigSpec.ConfigValue<String> foodDingot;
    public static ModConfigSpec.ConfigValue<String> foodDirt;
    public static ModConfigSpec.ConfigValue<String> foodDoubleChest;
    public static ModConfigSpec.ConfigValue<String> foodDubstep;
    public static ModConfigSpec.ConfigValue<String> foodEnchantingTable;
    public static ModConfigSpec.ConfigValue<String> foodEnderChest;
    public static ModConfigSpec.ConfigValue<String> foodEnderman;
    public static ModConfigSpec.ConfigValue<String> foodEndPortal;
    public static ModConfigSpec.ConfigValue<String> foodFlyingSaddle;
    public static ModConfigSpec.ConfigValue<String> foodFurnace;
    public static ModConfigSpec.ConfigValue<String> foodGhast;
    public static ModConfigSpec.ConfigValue<String> foodHeart;
    public static ModConfigSpec.ConfigValue<String> foodHouse;
    public static ModConfigSpec.ConfigValue<String> foodIlluminati;
    public static ModConfigSpec.ConfigValue<String> foodIronGolem;
    public static ModConfigSpec.ConfigValue<String> foodJuggernaut;
    public static ModConfigSpec.ConfigValue<String> foodJukebox;
    public static ModConfigSpec.ConfigValue<String> foodLead;
    public static ModConfigSpec.ConfigValue<String> foodLoot;
    public static ModConfigSpec.ConfigValue<String> foodMagmaCube;
    public static ModConfigSpec.ConfigValue<String> foodMickerson;
    public static ModConfigSpec.ConfigValue<String> foodMoon;
    public static ModConfigSpec.ConfigValue<String> foodMooshroom;
    public static ModConfigSpec.ConfigValue<String> foodNetherPortal;
    public static ModConfigSpec.ConfigValue<String> foodOcelot;
    public static ModConfigSpec.ConfigValue<String> foodPacMan;
    public static ModConfigSpec.ConfigValue<String> foodPig;
    public static ModConfigSpec.ConfigValue<String> foodPingot;
    public static ModConfigSpec.ConfigValue<String> foodPixie;
    public static ModConfigSpec.ConfigValue<String> foodPufferfish;
    public static ModConfigSpec.ConfigValue<String> foodPurpliciousCow;
    public static ModConfigSpec.ConfigValue<String> foodQuantumCrystalMonster;
    public static ModConfigSpec.ConfigValue<String> foodQuiver;
    public static ModConfigSpec.ConfigValue<String> foodSaddle;
    public static ModConfigSpec.ConfigValue<String> foodSheep;
    public static ModConfigSpec.ConfigValue<String> foodShield;
    public static ModConfigSpec.ConfigValue<String> foodSiamese;
    public static ModConfigSpec.ConfigValue<String> foodSilverfish;
    public static ModConfigSpec.ConfigValue<String> foodSlime;
    public static ModConfigSpec.ConfigValue<String> foodSnowGolem;
    public static ModConfigSpec.ConfigValue<String> foodSpider;
    public static ModConfigSpec.ConfigValue<String> foodSponge;
    public static ModConfigSpec.ConfigValue<String> foodSquid;
    public static ModConfigSpec.ConfigValue<String> foodSun;
    public static ModConfigSpec.ConfigValue<String> foodTorch;
    public static ModConfigSpec.ConfigValue<String> foodWither;
    public static ModConfigSpec.ConfigValue<String> foodWolf;
    public static ModConfigSpec.BooleanValue disableAnvil;
    public static ModConfigSpec.BooleanValue disableApple;
    public static ModConfigSpec.BooleanValue disableAprilFool;
    public static ModConfigSpec.BooleanValue disableBanana;
    public static ModConfigSpec.BooleanValue disableBed;
    public static ModConfigSpec.BooleanValue disableBiome;
    public static ModConfigSpec.BooleanValue disableBlackHole;
    public static ModConfigSpec.BooleanValue disableBlaze;
    public static ModConfigSpec.BooleanValue disableBrewingStand;
    public static ModConfigSpec.BooleanValue disableCheetah;
    public static ModConfigSpec.BooleanValue disableChest;
    public static ModConfigSpec.BooleanValue disableChicken;
    public static ModConfigSpec.BooleanValue disableChristmasTree;
    public static ModConfigSpec.BooleanValue disableCloud;
    public static ModConfigSpec.BooleanValue disableCobblestone;
    public static ModConfigSpec.BooleanValue disableCow;
    public static ModConfigSpec.BooleanValue disableCraftingTable;
    public static ModConfigSpec.BooleanValue disableCreeper;
    public static ModConfigSpec.BooleanValue disableDirt;
    public static ModConfigSpec.BooleanValue disableDoubleChest;
    public static ModConfigSpec.BooleanValue disableDubstep;
    public static ModConfigSpec.BooleanValue disableEnchantingTable;
    public static ModConfigSpec.BooleanValue disableEnderChest;
    public static ModConfigSpec.BooleanValue disableEnderman;
    public static ModConfigSpec.BooleanValue disableEndPortal;
    public static ModConfigSpec.BooleanValue disableFlyingSaddle;
    public static ModConfigSpec.BooleanValue disableFurnace;
    public static ModConfigSpec.BooleanValue disableGhast;
    public static ModConfigSpec.BooleanValue disableDingot;
    public static ModConfigSpec.BooleanValue disableHeart;
    public static ModConfigSpec.BooleanValue disableHouse;
    public static ModConfigSpec.BooleanValue disableIlluminati;
    public static ModConfigSpec.BooleanValue disableIronGolem;
    public static ModConfigSpec.BooleanValue disableJuggernaut;
    public static ModConfigSpec.BooleanValue disableJukebox;
    public static ModConfigSpec.BooleanValue disableLead;
    public static ModConfigSpec.BooleanValue disableLoot;
    public static ModConfigSpec.BooleanValue disableMagmaCube;
    public static ModConfigSpec.BooleanValue disableMenorah;
    public static ModConfigSpec.BooleanValue disableMeta;
    public static ModConfigSpec.BooleanValue disableMickerson;
    public static ModConfigSpec.BooleanValue disableMishumaaSaba;
    public static ModConfigSpec.BooleanValue disableMoon;
    public static ModConfigSpec.BooleanValue disableMooshroom;
    public static ModConfigSpec.BooleanValue disableNetherPortal;
    public static ModConfigSpec.BooleanValue disableOcelot;
    public static ModConfigSpec.BooleanValue disablePacMan;
    public static ModConfigSpec.BooleanValue disablePig;
    public static ModConfigSpec.BooleanValue disablePingot;
    public static ModConfigSpec.BooleanValue disablePixie;
    public static ModConfigSpec.BooleanValue disablePoliticallyCorrect;
    public static ModConfigSpec.BooleanValue disablePufferfish;
    public static ModConfigSpec.BooleanValue disablePurpliciousCow;
    public static ModConfigSpec.BooleanValue disableQuantumCrystalMonster;
    public static ModConfigSpec.BooleanValue disableQuiver;
    public static ModConfigSpec.BooleanValue disableSaddle;
    public static ModConfigSpec.BooleanValue disableSatedChest;
    public static ModConfigSpec.BooleanValue disableSatedDoubleChest;
    public static ModConfigSpec.BooleanValue disableSheep;
    public static ModConfigSpec.BooleanValue disableShield;
    public static ModConfigSpec.BooleanValue disableSiamese;
    public static ModConfigSpec.BooleanValue disableSilverfish;
    public static ModConfigSpec.BooleanValue disableSlime;
    public static ModConfigSpec.BooleanValue disableSnowGolem;
    public static ModConfigSpec.BooleanValue disableSpider;
    public static ModConfigSpec.BooleanValue disableSponge;
    public static ModConfigSpec.BooleanValue disableSquid;
    public static ModConfigSpec.BooleanValue disableSun;
    public static ModConfigSpec.BooleanValue disableTorch;
    public static ModConfigSpec.BooleanValue disableWither;
    public static ModConfigSpec.BooleanValue disableWolf;

    static {
        BUILDER.push("Inventory Pets Config Settings");
        frequencyTreeTops = BUILDER.comment("Frequency of Tree Tops (default: 5)").defineInRange("frequencyTreeTops", 5, 1, 10);
        frequencySkyDungeons = BUILDER.comment("Frequency of Sky Dungeons (default: 5)").defineInRange("frequencySkyDungeons", 5, 1, 10);
        frequencyUndergroundDungeons = BUILDER.comment("Frequency of Underground Dungeons (default: 5)").defineInRange("frequencyUndergroundDungeons", 5, 1, 10);
        frequencySeaCaveDungeons = BUILDER.comment("Frequency of Sea Cave Dungeons (default: 5)").defineInRange("frequencySeaCaveDungeons", 5, 1, 10);
        frequencyNetherDungeons = BUILDER.comment("Frequency of Nether Dungeons (default: 5)").defineInRange("frequencyNetherDungeons", 5, 1, 10);
        frequencySpaceDungeons = BUILDER.comment("Frequency of Space Dungeons (default: 5)").defineInRange("frequencySpaceDungeons", 5, 1, 10);
        disableTreeTops = BUILDER.comment("Turn off Tree Tops (default:false)").define("disableTreeTops", false);
        disableSkyDungeons = BUILDER.comment("Turn off Sky dungeons (default:false)").define("disableSkyDungeons", false);
        disableUndergroundDungeons = BUILDER.comment("Turn off Underground dungeons (default:false)").define("disableUndergroundDungeons", false);
        disableSeaCaveDungeons = BUILDER.comment("Turn off Sea Cave dungeons (default:false)").define("disableSeaCaveDungeons", false);
        disableNetherDungeons = BUILDER.comment("Turn off Nether dungeons (default:false)").define("disableNetherDungeons", false);
        disableSpaceDungeons = BUILDER.comment("Turn off Space dungeons (default:false)").define("disableSpaceDungeons", false);
        disableAllDungeons = BUILDER.comment("Turn off all dungeons (default:false)").define("disableAllDungeons", false);
        disableMobsSpawnInDungeons = BUILDER.comment("Disable mobs spawning in dungeons (default:false)").define("disableMobsSpawnInDungeons", false);
        disableTreeTopTNT = BUILDER.comment("Disable random TNT in Tree Top chests (default:false)").define("disableTreeTopTNT", false);
        disableHolidayPets = BUILDER.comment("Disable all holiday pets (default:false)").define("disableHolidayPets", false);
        disableAprilFoolHoliday = BUILDER.comment("Disable the April Fool pet and messages (default:false)").define("disableAprilFoolHoliday", false);
        yearroundAprilFool = BUILDER.comment("Allow April Fool all year round (default:false)").define("yearroundAprilFool", false);
        enableAprilFoolGriefPranks = BUILDER.comment("Allow more grieflike April Fools pranks (default:false)").define("enableAprilFoolGriefPranks", false);
        showHolidayMessages = BUILDER.comment("Display holiday messages during startup (default:true)").define("showHolidayMessages", true);
        holidayPetMonth = BUILDER.comment("Holiday Pet active month (default: 12)").defineInRange("holidayPetMonth", 12, 1, 12);
        enableBlackHoleAffectsPlayers = BUILDER.comment("Allow Black Hole pet abilities to affect other players (default:false)").define("enableBlackHoleAffectsPlayers", false);
        enablePufferfishAffectsPlayers = BUILDER.comment("Allow Pufferfish pet abilities to affect other players (default:false)").define("enablePufferfishAffectsPlayers", false);
        enableMoonAffectsPlayers = BUILDER.comment("Allow Moon pet abilities to affect other players (default:false)").define("enableMoonAffectsPlayers", false);
        enableDubstepAffectsPlayers = BUILDER.comment("Allow Dubstep pet abilities to affect other players (default:false)").define("enableDubstepAffectsPlayers", false);
        enableSunAffectsPlayers = BUILDER.comment("Allow Sun pet abilities to affect other players (default:false)").define("enableDubstepAffectsPlayers", false);
        allowPetrifierLegendaries = BUILDER.comment("Allow Petrifier to make legendary pets (default:false)").define("allowPetrifierLegendaries", false);
        disablePetrifier = BUILDER.comment("Disable the Petrifier (default:false)").define("disablePetrifier", false);
        enableLootWithFTBUltimine = BUILDER.comment("Enable Loot Pet with FTBUltimine installed (default:false)").define("enableLootWithFTBUltimine", false);
        disableRightClickMachines = BUILDER.comment("Disable Machines that can Activate items (default:false)").define("disableRightClickMachines", false);
        showSuggestors = BUILDER.comment("Display the names of the fans who suggested pets (default:true)").define("showSuggestors", true);
        showUpdateMessage = BUILDER.comment("Display the mod update message during startup (default:true)").define("showUpdateMessage", true);
        allPlayersMustBeInBed = BUILDER.comment("All players must be in bed for Bed Pet sleep ability (default:false)").define("allPlayersMustBeInBed", false);
        biomeSearchChunks = BUILDER.comment("Chunks Biome Pet will search through (default:96)").defineInRange("biomePetChunks", 96, 1, 225);
        chickenEffectLevel = BUILDER.comment("Chicken Pet speed (default: 3)").defineInRange("chickenEffectLevel", 3, 1, 10);
        cloudFlySpeed = BUILDER.comment("Cloud Pet fly speed (default:3)").defineInRange("cloudFlySpeed", 3, 1, 4);
        disableCloudFly = BUILDER.comment("Disable Cloud Fly ability (default:false)").define("disableCloudFly", false);
        disableCloudLightning = BUILDER.comment("Disable Cloud Pet lightning strike ability (default:false)").define("disableCloudLightning", false);
        disableCloudSound = BUILDER.comment("Disable Cloud Pet thunder sounds (default:false)").define("disableCloudSound", false);
        cowPetRemovesLevitation = BUILDER.comment("AbstractCow Pet removes Levitation (default:false)").define("cowPetRemovesLevitation", false);
        disableCreeperExplosion = BUILDER.comment("Disable Creeper Pet explosion ability (default:false)").define("disableCreeperExplosion", false);
        dingotIPStruturesOnly = BUILDER.comment("Dingot only looks for Inventory Pets structures (default:false)").define("dingotIPStructuresOnly", false);
        disableEndermanAutoTeleport = BUILDER.comment("Disable Enderman Pet auto-teleport (default:false)").define("disableEndermanAutoTeleport", false);
        disableSpongeWaterAbsorb = BUILDER.comment("Disable Sponge Pet absorb water (default:false)").define("disableSpongeWaterAbsorb", false);
        disableIlluminatiGiveItems = BUILDER.comment("Disable Illuminati Pet gives items ability (default:false)").define("disableIlluminatiGiveItems", false);
        illuminatiCraftedOnly = BUILDER.comment("Illuminati Pet only gives craftable items (default:true)").define("illuminatiCraftedOnly", true);
        illuminatiCooldown = BUILDER.comment("Illuminati cooldown duration in minutes (default: 1)").defineInRange("illuminatiCooldown", 1, 1, 10);
        illuminatiInvisibleDuration = BUILDER.comment("Illuminati invisibility duration in minutes (default: 1)").defineInRange("illuminatiInvisibleDuration", 1, 1, 3);
        illuminatiItemCapLimit = BUILDER.comment("Item cap for all loaded items, including mods (default: 5000)").defineInRange("illuminatiItemCapLimit", 5000, 1, 50000);
        juggernautCooldown = BUILDER.comment("Juggernaut cooldown duration in minutes (default: 1)").defineInRange("juggernautCooldown", 1, 1, 10);
        juggernautShieldWallDuration = BUILDER.comment("Juggernaut shield wall duration in minutes (default: 1)").defineInRange("juggernautShieldWallDuration", 1, 1, 3);
        pacManEatLevel = BUILDER.comment("Hunger threshold for Pac-man Pet to auto-eats (default: 8)").defineInRange("pacManEatLevel", 8, 1, 10);
        pacManPowerupFactor = BUILDER.comment("Factor by which PacMan Powerup bonus increases with every kill (default: 3)").defineInRange("pacManPowerupFactor", 3, 1, 10);
        disablePingotAutoExtract = BUILDER.comment("Disable Pingot Pet auto extract ability (default:false)").define("disablePingotAutoExtract", false);
        reduceQuantumCrystalMonsterMinions = BUILDER.comment("Reduce the number of Quantum Crystal Monster Pet minions (default:false)").define("reduceQuantumCrystalMonsterMinions", false);
        disableSlimeReviveSound = BUILDER.comment("Disable Slime revival sound (default:false)").define("disableSlimeReviveSound", false);
        disableSpiderJump = BUILDER.comment("Disable Spider Pet jump ability (default:false)").define("disableSpiderJump", false);
        disableSquidSpeed = BUILDER.comment("Disable Squid Pet swim speed boost ability (default:false)").define("disableSquidSpeed", false);
        spongeAbsorbBlockRadius = BUILDER.comment("Radius blocks of water absorbed by Sponge Pet (default: 8)").defineInRange("spongeAbsorbBlockRadius", 8, 1, 64);
        disablePetsGiveItems = BUILDER.comment("Disable Pets give items ability (default:false)").define("disablePetsGiveItems", false);
        petsMustEat = BUILDER.comment("Are pets required to eat food (default:true)").define("petsMustEat", true);
        petsEatWholeItems = BUILDER.comment("Pets eat rarer items (default:false)").gameRestart().define("petsEatWholeItems", false);
        petEatTimerFactor = BUILDER.comment("Frequency of Pet Eating (default: 120)").defineInRange("petEatTimerFactor", 120, 1, 5000);
        foodAnvil = BUILDER.comment("Anvil Pet's favorite food").define("foodAnvil", (Object)"minecraft:iron_nugget");
        foodApple = BUILDER.comment("Apple Pet's favorite food").define("foodApple", (Object)"minecraft:gold_ingot");
        foodAprilFool = BUILDER.comment("April Fool Pet's favorite food").define("foodAprilFool", (Object)"minecraft:tripwire_hook");
        foodBanana = BUILDER.comment("Banana Pet's favorite food").define("foodBanana", (Object)"minecraft:glowstone_dust");
        foodBed = BUILDER.comment("Bed Pet's favorite food").define("foodBed", (Object)"minecraft:white_wool");
        foodBiome = BUILDER.comment("Biome Pet's favorite food").define("foodBiome", (Object)"minecraft:grass_block");
        foodBlackHole = BUILDER.comment("Black Hole Pet's favorite food").define("foodBlackHole", (Object)"inventorypets:nugget_obsidian");
        foodBlaze = BUILDER.comment("Blaze Pet's favorite food").define("foodBlaze", (Object)"minecraft:quartz");
        foodBrewingStand = BUILDER.comment("Brewing Stand Pet's favorite food").define("foodBrewingStand", (Object)"minecraft:nether_wart");
        foodCheetah = BUILDER.comment("Cheetah Pet's favorite food").define("foodCheetah", (Object)"minecraft:beef");
        foodChest = BUILDER.comment("Chest Pet's favorite food").define("foodChest", (Object)"minecraft:oak_planks");
        foodChicken = BUILDER.comment("Chicken Pet's favorite food").define("foodChicken", (Object)"minecraft:wheat_seeds");
        foodCloud = BUILDER.comment("Cloud Pet's favorite food").define("foodCloud", (Object)"minecraft:quartz");
        foodCobblestone = BUILDER.comment("Cobblestone Pet's favorite food").define("foodCobblestone", (Object)"minecraft:dirt");
        foodCow = BUILDER.comment("AbstractCow Pet's favorite food").define("foodCow", (Object)"minecraft:wheat");
        foodCraftingTable = BUILDER.comment("Crafting Table Pet's favorite food").define("foodCraftingTable", (Object)"minecraft:oak_planks");
        foodCreeper = BUILDER.comment("Creeper Pet's favorite food").define("foodCreeper", (Object)"inventorypets:nugget_emerald");
        foodDingot = BUILDER.comment("Dingot Pet's favorite food").define("foodDingot", (Object)"minecraft:copper_ingot");
        foodDirt = BUILDER.comment("Dirt Pet's favorite food").define("foodDirt", (Object)"minecraft:cobblestone");
        foodDoubleChest = BUILDER.comment("Double Chest Pet's favorite food").define("foodDoubleChest", (Object)"minecraft:oak_log");
        foodDubstep = BUILDER.comment("Dubstep Pet's favorite food").define("foodDubstep", (Object)"minecraft:note_block");
        foodEnchantingTable = BUILDER.comment("Enchanting Table Pet's favorite food").define("foodEnchantingTable", (Object)"inventorypets:nugget_lapis");
        foodEnderChest = BUILDER.comment("Ender Chest Pet's favorite food").define("foodEnderChest", (Object)"inventorypets:nugget_ender");
        foodEnderman = BUILDER.comment("Enderman Pet's favorite food").define("foodEnderman", (Object)"inventorypets:nugget_obsidian");
        foodEndPortal = BUILDER.comment("End Portal Pet's favorite food").define("foodEndPortal", (Object)"inventorypets:nugget_ender");
        foodFlyingSaddle = BUILDER.comment("Flying Saddle Pet's favorite food").define("foodFlyingSaddle", (Object)"inventorypets:nugget_diamond");
        foodFurnace = BUILDER.comment("Furnace Pet's favorite food").define("foodFurnace", (Object)"inventorypets:nugget_coal");
        foodGhast = BUILDER.comment("Ghast Pet's favorite food").define("foodGhast", (Object)"minecraft:blaze_powder");
        foodHeart = BUILDER.comment("Heart Pet's favorite food").define("foodHeart", (Object)"minecraft:red_tulip");
        foodHouse = BUILDER.comment("House Pet's favorite food").define("foodHouse", (Object)"minecraft:iron_nugget");
        foodIronGolem = BUILDER.comment("Iron Golem Pet's favorite food").define("foodIronGolem", (Object)"minecraft:iron_ingot");
        foodIlluminati = BUILDER.comment("Illuminati Pet's favorite food").define("foodIlluminati", (Object)"inventorypets:nugget_emerald");
        foodJuggernaut = BUILDER.comment("Juggernaut Pet's favorite food").define("foodJuggernaut", (Object)"inventorypets:nugget_obsidian");
        foodJukebox = BUILDER.comment("Jukebox Pet's favorite food").define("foodJukebox", (Object)"minecraft:redstone");
        foodLead = BUILDER.comment("Lead Pet's favorite food").define("foodLead", (Object)"minecraft:string");
        foodLoot = BUILDER.comment("Loot Pet's favorite food").define("foodLoot", (Object)"minecraft:gold_nugget");
        foodMagmaCube = BUILDER.comment("Magma Cube Pet's favorite food").define("foodMagmaCube", (Object)"minecraft:quartz");
        foodMickerson = BUILDER.comment("Mickerson Pet's favorite food").define("foodMickerson", (Object)"inventorypets:nugget_diamond");
        foodMoon = BUILDER.comment("Moon Pet's favorite food").define("foodMoon", (Object)"inventorypets:nugget_emerald");
        foodMooshroom = BUILDER.comment("Mooshroom Pet's favorite food").define("foodMooshroom", (Object)"minecraft:red_mushroom");
        foodNetherPortal = BUILDER.comment("Nether Portal Pet's favorite food").define("foodNetherPortal", (Object)"inventorypets:nugget_obsidian");
        foodOcelot = BUILDER.comment("Ocelot Pet's favorite food").define("foodOcelot", (Object)"minecraft:cooked_cod");
        foodPacMan = BUILDER.comment("Pac-Man Pet's favorite food").define("foodPacMan", (Object)"minecraft:cookie");
        foodPig = BUILDER.comment("Pig Pet's favorite food").define("foodPig", (Object)"minecraft:carrot");
        foodPingot = BUILDER.comment("Pingot Pet's favorite food").define("foodPingot", (Object)"inventorypets:nugget_diamond");
        foodPixie = BUILDER.comment("Pixie Pet's favorite food").define("foodPixie", (Object)"inventorypets:nugget_emerald");
        foodPufferfish = BUILDER.comment("Pufferfish Pet's favorite food").define("foodPufferfish", (Object)"minecraft:glowstone_dust");
        foodPurpliciousCow = BUILDER.comment("Purplicious AbstractCow Pet's favorite food").define("foodPurpliciousCow", (Object)"inventorypets:nugget_diamond");
        foodQuantumCrystalMonster = BUILDER.comment("Quantum Crystal Monster Pet's favorite food").define("foodQuantumCrystalMonster", (Object)"inventorypets:nugget_lapis");
        foodQuiver = BUILDER.comment("Quiver Pet's favorite food").define("foodQuiver", (Object)"minecraft:feather");
        foodSaddle = BUILDER.comment("Saddle Pet's favorite food").define("foodSaddle", (Object)"minecraft:iron_nugget");
        foodSheep = BUILDER.comment("Sheep Pet's favorite food").define("foodSheep", (Object)"minecraft:wheat");
        foodShield = BUILDER.comment("Shield Pet's favorite food").define("foodShield", (Object)"minecraft:iron_nugget");
        foodSiamese = BUILDER.comment("Siamese Pet's favorite food").define("foodSiamese", (Object)"minecraft:cooked_chicken");
        foodSilverfish = BUILDER.comment("Silverfish Pet's favorite food").define("foodSilverfish", (Object)"minecraft:cobblestone");
        foodSlime = BUILDER.comment("Slime Pet's favorite food").define("foodSlime", (Object)"minecraft:golden_apple");
        foodSnowGolem = BUILDER.comment("Snow Golem Pet's favorite food").define("foodSnowGolem", (Object)"minecraft:pumpkin");
        foodSpider = BUILDER.comment("Spider Pet's favorite food").define("foodSpider", (Object)"minecraft:beef");
        foodSponge = BUILDER.comment("Sponge Pet's favorite food").define("foodSponge", (Object)"minecraft:lily_pad");
        foodSquid = BUILDER.comment("Squid Pet's favorite food").define("foodSquid", (Object)"minecraft:cod");
        foodSun = BUILDER.comment("Sun Pet's favorite food").define("foodSun", (Object)"minecraft:gold_ingot");
        foodTorch = BUILDER.comment("Torch Pet's favorite food").define("foodTorch", (Object)"inventorypets:nugget_coal");
        foodWither = BUILDER.comment("Wither Pet's favorite food").define("foodWither", (Object)"minecraft:soul_sand");
        foodWolf = BUILDER.comment("Wolf Pet's favorite food").define("foodWolf", (Object)"minecraft:bone");
        disableAnvil = BUILDER.comment("Disable the Anvil pet (default:false)").define("disableAnvil", false);
        disableApple = BUILDER.comment("Disable the Apple pet (default:false)").define("disableApple", false);
        disableAprilFool = BUILDER.comment("Disable the April Fool pet (default:false)").define("disableAprilFool", false);
        disableBanana = BUILDER.comment("Disable the Banana pet (default:false)").define("disableBanana", false);
        disableBed = BUILDER.comment("Disable the Bed pet (default:false)").define("disableBed", false);
        disableBiome = BUILDER.comment("Disable the Biome pet (default:false)").define("disableBiome", false);
        disableBlackHole = BUILDER.comment("Disable the Black Hole pet (default:false)").define("disableBlackHole", false);
        disableBlaze = BUILDER.comment("Disable the Blaze pet (default:false)").define("disableBlaze", false);
        disableBrewingStand = BUILDER.comment("Disable the Brewing Stand pet (default:false)").define("disableBrewingStand", false);
        disableCheetah = BUILDER.comment("Disable the Blaze pet (default:false)").define("disableCheetah", false);
        disableChest = BUILDER.comment("Disable the Chest pet (default:false)").define("disableChest", false);
        disableChicken = BUILDER.comment("Disable the Chicken pet (default:false)").define("disableChicken", false);
        disableChristmasTree = BUILDER.comment("Disable the Christmas Tree pet (default:false)").define("disableChristmasTree", false);
        disableCloud = BUILDER.comment("Disable the Cloud pet (default:false)").define("disableCloud", false);
        disableCobblestone = BUILDER.comment("Disable the Cobblestone pet (default:false)").define("disableCobblestone", false);
        disableCow = BUILDER.comment("Disable the AbstractCow pet (default:false)").define("disableCow", false);
        disableCraftingTable = BUILDER.comment("Disable the Crafting Table pet (default:false)").define("disableCraftingTable", false);
        disableCreeper = BUILDER.comment("Disable the Creeper pet (default:false)").define("disableCreeper", false);
        disableDirt = BUILDER.comment("Disable the Dirt pet (default:false)").define("disableDirt", false);
        disableDingot = BUILDER.comment("Disable the Dingot pet (default:false)").define("disableDingot", false);
        disableDoubleChest = BUILDER.comment("Disable the Double Chest pet (default:false)").define("disableDoubleChest", false);
        disableDubstep = BUILDER.comment("Disable the Dubstep pet (default:false)").define("disableDubstep", false);
        disableEnchantingTable = BUILDER.comment("Disable the Enchanting Table pet (default:false)").define("disableEnchantingTable", false);
        disableEnderChest = BUILDER.comment("Disable the Ender Chest pet (default:false)").define("disableEnderChest", false);
        disableEnderman = BUILDER.comment("Disable the Enderman pet (default:false)").define("disableEnderman", false);
        disableEndPortal = BUILDER.comment("Disable the End Portal pet (default:false)").define("disableEndPortal", false);
        disableFlyingSaddle = BUILDER.comment("Disable the Flying Saddle pet (default:false)").define("disableFlyingSaddle", false);
        disableFurnace = BUILDER.comment("Disable the Furnace pet (default:false)").define("disableFurnace", false);
        disableGhast = BUILDER.comment("Disable the Ghast pet (default:false)").define("disableGhast", false);
        disableHeart = BUILDER.comment("Disable the Heart pet (default:false)").define("disableHeart", false);
        disableHouse = BUILDER.comment("Disable the House pet (default:false)").define("disableHouse", false);
        disableIlluminati = BUILDER.comment("Disable the Illuminati pet (default:false)").define("disableIlluminati", false);
        disableIronGolem = BUILDER.comment("Disable the Iron Golem pet (default:false)").define("disableIronGolem", false);
        disableJuggernaut = BUILDER.comment("Disable the Juggernaut pet (default:false)").define("disableJuggernaut", false);
        disableJukebox = BUILDER.comment("Disable the Jukebox pet (default:false)").define("disableJukebox", false);
        disableLead = BUILDER.comment("Disable the Lead pet (default:false)").define("disableLead", false);
        disableLoot = BUILDER.comment("Disable the Loot pet (default:false)").define("disableLoot", false);
        disableMagmaCube = BUILDER.comment("Disable the Magma Cube pet (default:false)").define("disableMagmaCube", false);
        disableMenorah = BUILDER.comment("Disable the Menorah pet (default:false)").define("disableMenorah", false);
        disableMeta = BUILDER.comment("Disable the Meta pet (default:false)").define("disableMeta", false);
        disableMickerson = BUILDER.comment("Disable the Mickerson pet (default:false)").define("disableMickerson", false);
        disableMishumaaSaba = BUILDER.comment("Disable the Mishumaa Saba pet (default:false)").define("disableMishumaaSaba", false);
        disableMoon = BUILDER.comment("Disable the Moon pet (default:false)").define("disableMoon", false);
        disableMooshroom = BUILDER.comment("Disable the Mooshroom pet (default:false)").define("disableMooshroom", false);
        disableNetherPortal = BUILDER.comment("Disable the Nether Portal pet (default:false)").define("disableNetherPortal", false);
        disableOcelot = BUILDER.comment("Disable the Ocelot pet (default:false)").define("disableOcelot", false);
        disablePacMan = BUILDER.comment("Disable the PacMan pet (default:false)").define("disablePacMan", false);
        disablePig = BUILDER.comment("Disable the Pig pet (default:false)").define("disablePig", false);
        disablePingot = BUILDER.comment("Disable the Pingot pet (default:false)").define("disablePingot", false);
        disablePixie = BUILDER.comment("Disable the Pixie pet (default:false)").define("disablePixie", false);
        disablePoliticallyCorrect = BUILDER.comment("Disable the Politically Correct pet (default:false)").define("disablePoliticallyCorrect", false);
        disablePufferfish = BUILDER.comment("Disable the Pufferfish pet (default:false)").define("disablePufferfish", false);
        disablePurpliciousCow = BUILDER.comment("Disable the Purplicious AbstractCow pet (default:false)").define("disablePurpliciousCow", false);
        disableQuantumCrystalMonster = BUILDER.comment("Disable the Quantum Crystal Monster pet (default:false)").define("disableQuantumCrystalMonster", false);
        disableQuiver = BUILDER.comment("Disable the Quiver pet (default:false)").define("disableQuiver", false);
        disableSaddle = BUILDER.comment("Disable the Saddle pet (default:false)").define("disableSaddle", false);
        disableSatedChest = BUILDER.comment("Disable the Sated Chest pet (default:false)").define("disableSatedChest", false);
        disableSatedDoubleChest = BUILDER.comment("Disable the Sated Double Chest pet (default:false)").define("disableSatedDoubleChest", false);
        disableSheep = BUILDER.comment("Disable the Sheep pet (default:false)").define("disableSheep", false);
        disableShield = BUILDER.comment("Disable the Shield pet (default:false)").define("disableShield", false);
        disableSiamese = BUILDER.comment("Disable the Siamese pet (default:false)").define("disableSiamese", false);
        disableSilverfish = BUILDER.comment("Disable the Silverfish pet (default:false)").define("disableSilverfish", false);
        disableSlime = BUILDER.comment("Disable the Slime pet (default:false)").define("disableSlime", false);
        disableSnowGolem = BUILDER.comment("Disable the Snow Golem pet (default:false)").define("disableSnowGolem", false);
        disableSpider = BUILDER.comment("Disable the Spider pet (default:false)").define("disableSpider", false);
        disableSponge = BUILDER.comment("Disable the Sponge pet (default:false)").define("disableSponge", false);
        disableSquid = BUILDER.comment("Disable the Squid pet (default:false)").define("disableSquid", false);
        disableSun = BUILDER.comment("Disable the Sun pet (default:false)").define("disableSun", false);
        disableTorch = BUILDER.comment("Disable the Torch pet (default:false)").define("disableTorch", false);
        disableWither = BUILDER.comment("Disable the Wither pet (default:false)").define("disableWither", false);
        disableWolf = BUILDER.comment("Disable the Wolf pet (default:false)").define("disableWolf", false);
        BUILDER.pop();
        SPEC = BUILDER.build();
    }
}
