name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          distribution: microsoft
          java-version: "21"

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: generate checksum
        run: sha256sum build/libs/*.jar > build/libs/SHA256SUMS.txt

      - name: publish release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
            build/libs/SHA256SUMS.txt
          generate_release_notes: true
